### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Allan-Xu** [QWTforGithub/PUDM#14]
感谢作者开源的代码，按照readme安装好虚拟环境后，没有遇到报错，很顺利。不过开始训练的时候遇到了此问题，我的卡是A40，并且我也指定了设备，感谢您的解答。

代码
![Screenshot 2024-10-31 at 20 52 11](https://github.com/user-attachments/assets/5272d26e-615a-4df6-a6b7-01abee1901fa)

这是环境配置：
conda list
# packages in environment at /home/xjc/anaconda3/envs/pcdm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
black                     23.3.0                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
ca-certificates           2024.9.24            h06a4308_0  
cachetools                5.5.0                    pypi_0    pypi
certifi                   2022.12.7        py37h06a4308_0  
cffi                      1.15.1                   pypi_0    pypi
chamfer-3d                0.0.0                    pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
cudatoolkit               11.8.0               h6a678d5_0  
cycler                    0.11.0                   pypi_0    pypi
dash                      2.15.0                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.7.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
flake8                    5.0.4                    pypi_0    pypi
flask                     2.2.5                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
google-auth               2.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.62.3                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
hydra-core                0.11.3                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.31.2                   pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.1.5                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
json5                     0.9.16                   pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.1.1                    pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              4.12.0                   pypi_0    pypi
jupyter-server            1.24.0                   pypi_0    pypi
jupyterlab                3.5.3                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.15.2                   pypi_0    pypi
jupyterlab-widgets        3.0.13                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0  
libcst                    1.0.1                    pypi_0    pypi
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lmdb                      1.5.1                    pypi_0    pypi
markdown                  3.3                      pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
moreorless                0.4.0                    pypi_0    pypi
msgpack                   1.0.5                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclassic                 1.1.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.6.0                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.5.7                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
nvidia-cublas-cu11        11.11.3.6                pypi_0    pypi
nvidia-cudnn-cu11         9.5.1.17                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 1.4.1                    pypi_0    pypi
open3d                    0.17.0                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 24.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.11.2                   pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.0.0                    pypi_0    pypi
plotly                    5.18.0                   pypi_0    pypi
pointnet2                 3.0.0                    pypi_0    pypi
pointnet2-ops             3.0.0                    pypi_0    pypi
pointops                  0.0.0                    pypi_0    pypi
portalocker               2.7.0                    pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycodestyle               2.9.1                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyflakes                  2.5.0                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.7.16               h7a1cb2a_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         0.7.1                    pypi_0    pypi
pytorch3d                 0.6.1           py37_cu111_pyt191    <unknown>
pytz                      2024.2                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     26.2.0                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
stdlibs                   2022.10.9                pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.2.3                    pypi_0    pypi
tensorboard               2.11.2                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     1.9.1+cu111              pypi_0    pypi
torchaudio                0.9.1                    pypi_0    pypi
torchvision               0.10.1+cu111             pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.66.6                   pypi_0    pypi
trailrunner               1.4.0                    pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transforms3d              0.3.1                    pypi_0    pypi
typed-ast                 1.5.5                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
usort                     1.0.8.post1              pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py37h06a4308_0  
widgetsnbextension        4.0.13                   pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  

这是报错内容：
python train.py --dataset PUGAN
The configuration is:
{
    "diffusion_config": {
        "T": 1000,
        "beta_0": 0.0001,
        "beta_T": 0.02
    },
    "pointnet_config": {
        "model_name": "pointnet",
        "in_fea_dim": 3,
        "partial_in_fea_dim": 0,
        "out_dim": 3,
        "include_t": true,
        "t_dim": 128,
        "model.use_xyz": true,
        "attach_position_to_input_feature": true,
        "include_abs_coordinate": true,
        "include_center_coordinate": true,
        "record_neighbor_stats": false,
        "bn_first": false,
        "bias": true,
        "res_connect": true,
        "map_type": "cross_attention",
        "condition_loss": true,
        "include_class_condition": true,
        "num_class": 256,
        "class_condition_dim": 128,
        "gamma": 0.5,
        "bn": true,
        "include_local_feature": true,
        "include_global_feature": true,
        "global_feature_remove_last_activation": false,
        "pnet_global_feature_architecture": "[[3, 128, 256], [512, 1024]]",
        "attention_setting": {
            "use_attention_module": true,
            "attention_bn": true,
            "transform_grouped_feat_out": true,
            "last_activation": true,
            "add_attention_to_FeatureMapper_module": true
        },
        "architecture": {
            "npoint": "[1024, 256, 64, 16]",
            "radius": "[0.1, 0.2, 0.4, 0.8]",
            "neighbor_definition": "radius",
            "nsample": "[32, 32, 32, 32]",
            "feature_dim": "[32, 64, 128, 256, 512]",
            "mlp_depth": 3,
            "decoder_feature_dim": "[128, 128, 256, 256, 512]",
            "include_grouper": false,
            "decoder_mlp_depth": 2,
            "use_knn_FP": true,
            "K": 8
        },
        "condition_net_architecture": {
            "npoint": "[1024, 256, 64, 16]",
            "radius": "[0.1, 0.2, 0.4, 0.8]",
            "neighbor_definition": "radius",
            "nsample": "[32, 32, 32, 32]",
            "feature_dim": "[32, 32, 64, 64, 128]",
            "mlp_depth": 3,
            "decoder_feature_dim": "[32, 32, 64, 64, 128]",
            "include_grouper": false,
            "decoder_mlp_depth": 2,
            "use_knn_FP": true,
            "K": 8
        },
        "feature_mapper_architecture": {
            "neighbor_definition": "radius",
            "encoder_feature_map_dim": "[32, 32, 64, 64]",
            "encoder_mlp_depth": 2,
            "encoder_radius": "[0.1, 0.2, 0.4, 0.8]",
            "encoder_nsample": "[32, 32, 32, 32]",
            "decoder_feature_map_dim": "[32, 32, 64, 64, 128]",
            "decoder_mlp_depth": 2,
            "decoder_radius": "[0.1, 0.2, 0.4, 0.8, 1.6]",
            "decoder_nsample": "[32, 32, 32, 32, 32]"
        }
    },
    "train_config": {
        "dataset": "PUGAN",
        "root_directory": "exp_pugan",
        "output_directory": "logs/checkpoint",
        "tensorboard_directory": "logs/tensorboard",
        "epochs_per_ckpt": 10,
        "iters_per_logging": 50,
        "n_epochs": 2000,
        "learning_rate": 0.0002
    },
    "pugan_dataset_config": {
        "dataset": "PUGAN",
        "data_dir": "/home/xjc/project/genpcc/data/pugan/PU-GAN",
        "npoints": 2048,
        "novel_input": false,
        "novel_input_only": false,
        "scale": 1,
        "batch_size": 28,
        "eval_batch_size": 28,
        "num_workers": 4,
        "num_samples_tested": 1600,
        "test_trainset_during_eval": true,
        "include_generated_samples": false,
        "augmentation": {
            "pc_augm_scale": 1.2,
            "pc_augm_rot": true,
            "pc_rot_scale": 90,
            "pc_augm_mirror_prob": 0.5,
            "pc_augm_jitter": false,
            "translation_magnitude": 0.1,
            "noise_magnitude_for_generated_samples": 0
        },
        "R": 4
    },
    "gen_config": {
        "ckpt_path": "logs/checkpoint"
    }
}
output directory is exp_pugan/PUGAN/logs/checkpoint
Config file has been copied from ./exp_configs/PUGAN.json to exp_pugan/PUGAN/logs/checkpoint/PUGAN.json
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    **train_config
  File "train.py", line 62, in train
    diffusion_hyperparams[key] = diffusion_hyperparams[key].cuda()
RuntimeError: CUDA error: out of memory

**Comment by QWTforGithub** [comment]
你好，我按照自己的readme重新配置了一下PUDM，没有发现显存溢出的情况。
![image](https://github.com/user-attachments/assets/7773d1c7-ad1e-4398-b7fa-88103935a794)
我使用的4090 GPU，24显存，你的A40是40G吗？那不太可能显存溢出。你在训练时，确实卡5是没有其他程序占用吗？

**Comment by Allan-Xu** [comment]
感谢你的回复，没有程序占用呢，我再重新配个环境试一下，谢谢咯

**Comment by QWTforGithub** [comment]
我配置环境时，遵循了以下步骤：
1. 安装依赖包
`conda create -n pudm python=3.7 -y
conda activate pudm

conda install cudatoolkit
pip install nvidia-cudnn-cu11

pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

pip install open3d termcolor tqdm einops transforms3d==0.3.1
pip install msgpack-numpy lmdb h5py hydra-core==0.11.3 pytorch-lightning==0.7.1
pip install scikit-image black usort flake8 matplotlib jupyter imageio fvcore plotly opencv-python
pip install markdown==3.1.0

# For installing pytorch3d, please follow:
1. download pytorch3d-0.6.1-py37_cu111_pyt191.tar.bz2 from https://anaconda.org/pytorch3d/pytorch3d/files?page=10
2. conda install pytorch3d-0.6.1-py37_cu111_pyt191.tar.bz2

# compile C++ extension packages
sh compile.sh`
2. 下载checkpoint，放到PUDM-main/pointnet2/pkls中，先测试了一下
python example_samples.py --dataset PUGAN --R 4 --step 30 --example_file ./example/pig.xyz
3. 下载PUGAN的数据集，并在PUGAN.json更改了数据集路径
PUGAN_poisson_256_poisson_1024.h5
4. 执行训练
python train.py --dataset PUGAN

你可以按照我的步骤尝试一下。

**Comment by Allan-Xu** [comment]
好的好的，十分感谢

**Comment by Allan-Xu** [comment]
> 我配置环境时，遵循了以下步骤：
> 
> 1. 安装依赖包
>    `conda create -n pudm python=3.7 -y
>    conda activate pudm
> 
> conda install cudatoolkit pip install nvidia-cudnn-cu11
> 
> pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
> 
> pip install open3d termcolor tqdm einops transforms3d==0.3.1 pip install msgpack-numpy lmdb h5py hydra-core==0.11.3 pytorch-lightning==0.7.1 pip install scikit-image black usort flake8 matplotlib jupyter imageio fvcore plotly opencv-python pip install markdown==3.1.0
> 
> For installing pytorch3d, please follow:
> 
> 1. download pytorch3d-0.6.1-py37_cu111_pyt191.tar.bz2 from https://anaconda.org/pytorch3d/pytorch3d/files?page=10
> 2. conda install pytorch3d-0.6.1-py37_cu111_pyt191.tar.bz2
> 
> compile C++ extension packages sh compile.sh` 2. 下载checkpoint，放到PUDM-main/pointnet2/pkls中，先测试了一下 python example_samples.py --dataset PUGAN --R 4 --step 30 --example_file ./example/pig.xyz 3. 下载PUGAN的数据集，并在PUGAN.json更改了数据集路径 PUGAN_poisson_256_poisson_1024.h5 4. 执行训练 python train.py --dataset PUGAN
> 
> 你可以按照我的步骤尝试一下。


pointnet2配置也没问题，没有报错
![Screenshot 2024-11-01 at 16 27 40](https://github.com/user-attachments/assets/db16f929-12fe-4924-879a-2e0d73a65910)

这个测试的时候报错的错
![Screenshot 2024-11-01 at 16 40 57](https://github.com/user-attachments/assets/dcb1b67f-de4a-419d-92d8-fa8332abc14b)

不好意思，完全按照你说的步骤试了下，还是存在cuda溢出的问题，我再摸索下是不是A40卡需要cuda版本要对应起来，安装过程中
conda install cudatoolkit
pip install nvidia-cudnn-cu11
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
我好像看到他自己安装了11.8，谢谢咯

**Comment by QWTforGithub** [comment]
有可能大概率你不是用的你指定的卡跑的，因为代码里指定了卡号。在example_samples.py中把os.environ['CUDA_VISIBLE_DEVICES'] = args.device_ids删除。然后，这样运行代码：
CUDA_VISIBLE_DEVICES=没有其他程序的卡号 python example_samples.py --dataset PUGAN --R 4 --step 30 --example_file ./example/pig.xyz

**Comment by Allan-Xu** [comment]
再次谢谢作者开源的代码，我解决了此问题，我把所有的.cuda( )改为.to(device)，就解决了cuda溢出的问题，不是安装环境的问题，谢谢了
